
import { createRequire } from 'module';
const require = createRequire(import.meta.url);

var rsiscool = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var h=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da=Object.assign({},h),ea="./this.program",fa="",ha,ia,ja,fs=require("fs"),ka=require("path");fa=require("url").fileURLToPath(new URL("./",import.meta.url));ha=a=>{a=la(a)?new URL(a):ka.normalize(a);return fs.readFileSync(a,void 0)};ja=a=>{a=ha(a);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c)=>{a=la(a)?new URL(a):ka.normalize(a);fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})};
!h.thisProgram&&1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);var ma=h.print||console.log.bind(console),n=h.printErr||console.error.bind(console);Object.assign(h,da);da=null;h.thisProgram&&(ea=h.thisProgram);var na;h.wasmBinary&&(na=h.wasmBinary);var oa,pa=!1,t,x,z,qa,B,C,ra,sa,ta=[],ua=[],va=[];function wa(){var a=h.preRun.shift();ta.unshift(a)}var D=0,xa=null,E=null;
function F(a){h.onAbort?.(a);a="Aborted("+a+")";n(a);pa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),la=a=>a.startsWith("file://"),za;function Aa(a){if(a==za&&na)return new Uint8Array(na);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}
function Ba(){var a=za;return na?Promise.resolve().then(()=>Aa(a)):new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),()=>{try{b(Aa(a))}catch(d){c(d)}})})}function Ca(a,b){return Ba().then(c=>WebAssembly.instantiate(c,a)).then(b,c=>{n(`failed to asynchronously prepare wasm: ${c}`);F(c)})}function Da(a,b){return Ca(a,b)}var G,Ea,Fa=a=>{for(;0<a.length;)a.shift()(h)};class Ga{constructor(a){this.ma=a-24}}
var Ha=0,Ia=0,Ja,I=a=>{for(var b="";x[a];)b+=Ja[x[a++]];return b},J={},K={},Ka={},L,La=a=>{throw new L(a);},Ma,Na=(a,b)=>{function c(m){m=b(m);if(m.length!==d.length)throw new Ma("Mismatched type converter count");for(var p=0;p<d.length;++p)M(d[p],m[p])}var d=[];d.forEach(function(m){Ka[m]=a});var e=Array(a.length),f=[],l=0;a.forEach((m,p)=>{K.hasOwnProperty(m)?e[p]=K[m]:(f.push(m),J.hasOwnProperty(m)||(J[m]=[]),J[m].push(()=>{e[p]=K[m];++l;l===f.length&&c(e)}))});0===f.length&&c(e)};
function Oa(a,b,c={}){var d=b.name;if(!a)throw new L(`type "${d}" must have a positive integer typeid pointer`);if(K.hasOwnProperty(a)){if(c.Da)return;throw new L(`Cannot register type '${d}' twice`);}K[a]=b;delete Ka[a];J.hasOwnProperty(a)&&(b=J[a],delete J[a],b.forEach(e=>e()))}function M(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Oa(a,b,c)}
var Qa=[],N=[],Ra=a=>{9<a&&0===--N[a+1]&&(N[a]=void 0,Qa.push(a))},O=a=>{if(!a)throw new L("Cannot use deleted val. handle = "+a);return N[a]},P=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Qa.pop()||N.length;N[b]=a;N[b+1]=1;return b}};function Sa(a){return this.fromWireType(C[a>>2])}
var Ta={name:"emscripten::val",fromWireType:a=>{var b=O(a);Ra(a);return b},toWireType:(a,b)=>P(b),argPackAdvance:8,readValueFromPointer:Sa,aa:null},Ua=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ra[c>>2])};case 8:return function(c){return this.fromWireType(sa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Va=(a,b)=>Object.defineProperty(b,"name",{value:a}),Wa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Xa(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].aa)return!0;return!1}function Ya(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Va(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var Za=(a,b)=>{if(void 0===h[a].Y){var c=h[a];h[a]=function(...d){if(!h[a].Y.hasOwnProperty(d.length))throw new L(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].Y})!`);return h[a].Y[d.length].apply(this,d)};h[a].Y=[];h[a].Y[c.Ba]=c}},$a=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].Y&&void 0!==h[a].Y[c])throw new L(`Cannot register public name '${a}' twice`);Za(a,a);if(h.hasOwnProperty(c))throw new L(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].Y[c]=b}else h[a]=b,void 0!==c&&(h[a].Wa=c)},ab=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(C[b+4*d>>2]);return c},bb=[],cb,db=a=>{var b=bb[a];b||(a>=bb.length&&(bb.length=a+1),bb[a]=b=cb.get(a));return b},eb=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,h["dynCall_"+a])(b,...c)):b=db(b)(...c);return b},fb=(a,b)=>(...c)=>eb(a,b,c),gb=(a,b)=>{a=I(a);var c=a.includes("j")?fb(a,b):db(b);if("function"!=typeof c)throw new L(`unknown function pointer with signature ${a}: ${b}`);return c},hb,
jb=a=>{a=ib(a);var b=I(a);Q(a);return b},kb=(a,b)=>{function c(f){e[f]||K[f]||(Ka[f]?Ka[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new hb(`${a}: `+d.map(jb).join([", "]));},lb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},mb=(a,b,c)=>{switch(b){case 1:return c?d=>t[d]:d=>x[d];case 2:return c?d=>z[d>>1]:d=>qa[d>>1];case 4:return c?d=>B[d>>2]:d=>C[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},nb=(a,b,c,d)=>{if(!(0<d))return 0;
var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.charCodeAt(f);if(55296<=l&&57343>=l){var m=a.charCodeAt(++f);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e},ob=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):
b+=3}return b},pb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,R=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&pb)return pb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
qb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,rb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&qa[c];)++c;c<<=1;if(32<c-a&&qb)return qb.decode(x.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=z[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},sb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},tb=a=>2*a.length,ub=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=B[a+
4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},vb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}B[b>>2]=f;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d},wb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},xb=(a,b)=>{var c=K[a];if(void 0===
c)throw a=`${b} has unknown type ${jb(a)}`,new L(a);return c},yb=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(C[b>>2]=P(d));return a},zb=[],Ab={},Bb=a=>{var b=Ab[a];return void 0===b?I(a):b},Cb=()=>"object"==typeof globalThis?globalThis:Function("return this")(),Db=a=>{var b=zb.length;zb.push(a);return b},Eb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=xb(C[b+4*d>>2],"parameter "+d);return c},Fb={},Hb=()=>{if(!Gb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Fb)void 0===Fb[b]?delete a[b]:a[b]=Fb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Gb=c}return Gb},Gb,Ib=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Jb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ib(a.split("/").filter(d=>
!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Kb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Lb=a=>{if("/"===a)return"/";a=Jb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Mb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);try{var a=require("crypto");if(a.randomFillSync)return c=>
a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}F("initRandomDevice")},Nb=a=>(Nb=Mb())(a),Ob=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ib(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Pb=[];function Qb(a,b){var c=Array(ob(a)+1);a=nb(a,c,0,c.length);b&&(c.length=a);return c}
var Tb=[];function Ub(a,b){Tb[a]={input:[],output:[],ha:b};Vb(a,Wb)}
var Wb={open(a){var b=Tb[a.node.rdev];if(!b)throw new S(43);a.tty=b;a.seekable=!1},close(a){a.tty.ha.fsync(a.tty)},fsync(a){a.tty.ha.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ha.xa)throw new S(60);for(var e=0,f=0;f<d;f++){try{var l=a.tty.ha.xa(a.tty)}catch(m){throw new S(29);}if(void 0===l&&0===e)throw new S(6);if(null===l||void 0===l)break;e++;b[c+f]=l}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ha.qa)throw new S(60);try{for(var e=0;e<d;e++)a.tty.ha.qa(a.tty,b[c+
e])}catch(f){throw new S(29);}d&&(a.node.timestamp=Date.now());return e}},Xb={xa(){a:{if(!Pb.length){var a=null;var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"));if(!a){a=null;break a}Pb=Qb(a,!0)}a=Pb.shift()}return a},qa(a,b){null===b||10===b?(ma(R(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(ma(R(a.output,0)),a.output=[])},Ta(){return{Pa:25856,
Ra:5,Oa:191,Qa:35387,Na:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ua(){return 0},Va(){return[24,80]}},Yb={qa(a,b){null===b||10===b?(n(R(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(n(R(a.output,0)),a.output=[])}};function Zb(a,b){var c=a.U?a.U.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.U,a.U=new Uint8Array(b),0<a.W&&a.U.set(c.subarray(0,a.W),0))}
var T={X:null,ba(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.X||(T.X={dir:{node:{da:T.O.da,Z:T.O.Z,lookup:T.O.lookup,ka:T.O.ka,rename:T.O.rename,unlink:T.O.unlink,rmdir:T.O.rmdir,readdir:T.O.readdir,symlink:T.O.symlink},stream:{ea:T.V.ea}},file:{node:{da:T.O.da,Z:T.O.Z},stream:{ea:T.V.ea,read:T.V.read,write:T.V.write,ta:T.V.ta,ya:T.V.ya,Aa:T.V.Aa}},link:{node:{da:T.O.da,Z:T.O.Z,readlink:T.O.readlink},stream:{}},ua:{node:{da:T.O.da,
Z:T.O.Z},stream:$b}});c=ac(a,b,c,d);16384===(c.mode&61440)?(c.O=T.X.dir.node,c.V=T.X.dir.stream,c.U={}):32768===(c.mode&61440)?(c.O=T.X.file.node,c.V=T.X.file.stream,c.W=0,c.U=null):40960===(c.mode&61440)?(c.O=T.X.link.node,c.V=T.X.link.stream):8192===(c.mode&61440)&&(c.O=T.X.ua.node,c.V=T.X.ua.stream);c.timestamp=Date.now();a&&(a.U[b]=c,a.timestamp=c.timestamp);return c},Sa(a){return a.U?a.U.subarray?a.U.subarray(0,a.W):new Uint8Array(a.U):new Uint8Array(0)},O:{da(a){var b={};b.dev=8192===(a.mode&
61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.W:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ca=4096;b.blocks=Math.ceil(b.size/b.Ca);return b},Z(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.W!=b))if(0==b)a.U=null,a.W=0;else{var c=
a.U;a.U=new Uint8Array(b);c&&a.U.set(c.subarray(0,Math.min(b,a.W)));a.W=b}},lookup(){throw bc[44];},ka(a,b,c,d){return T.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=cc(b,c)}catch(f){}if(d)for(var e in d.U)throw new S(55);}delete a.parent.U[a.name];a.parent.timestamp=Date.now();a.name=c;b.U[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.U[b];a.timestamp=Date.now()},rmdir(a,b){var c=cc(a,b),d;for(d in c.U)throw new S(55);delete a.U[b];a.timestamp=Date.now()},readdir(a){var b=
[".",".."],c;for(c of Object.keys(a.U))b.push(c);return b},symlink(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},V:{read(a,b,c,d,e){var f=a.node.U;if(e>=a.node.W)return 0;a=Math.min(a.node.W-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.U||a.U.subarray)){if(f)return a.U=b.subarray(c,c+d),
a.W=d;if(0===a.W&&0===e)return a.U=b.slice(c,c+d),a.W=d;if(e+d<=a.W)return a.U.set(b.subarray(c,c+d),e),d}Zb(a,e+d);if(a.U.subarray&&b.subarray)a.U.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.U[e+f]=b[c+f];a.W=Math.max(a.W,e+d);return d},ea(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.W);if(0>b)throw new S(28);return b},ta(a,b,c){Zb(a.node,b+c);a.node.W=Math.max(a.node.W,b+c)},ya(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.U;if(e&2||a.buffer!==
t.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;F();b=void 0;if(!b)throw new S(48);t.set(a,b)}else c=!1,b=a.byteOffset;return{ma:b,Ma:c}},Aa(a,b,c,d){T.V.write(a,b,0,d,c,!1);return 0}}},dc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ec=null,fc={},gc=[],hc=1,U=null,ic=!0,S=class{constructor(a){this.name="ErrnoError";this.ja=a}},bc={},jc=class{constructor(){this.ia={};this.node=null}get flags(){return this.ia.flags}set flags(a){this.ia.flags=
a}get position(){return this.ia.position}set position(a){this.ia.position=a}},kc=class{constructor(a,b,c,d){a||=this;this.parent=a;this.ba=a.ba;this.la=null;this.id=hc++;this.name=b;this.mode=c;this.O={};this.V={};this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function V(a,b={}){a=Ob(a);if(!a)return{path:"",node:null};b=Object.assign({wa:!0,ra:0},b);if(8<b.ra)throw new S(32);a=a.split("/").filter(l=>!!l);for(var c=ec,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=cc(c,a[e]);d=Jb(d+"/"+a[e]);c.la&&(!f||f&&b.wa)&&(c=c.la.root);if(!f||b.va)for(f=0;40960===(c.mode&61440);)if(c=lc(d),d=Ob(Kb(d),c),c=V(d,{ra:b.ra+1}).node,40<f++)throw new S(32);}return{path:d,node:c}}
function mc(a){for(var b;;){if(a===a.parent)return a=a.ba.za,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function nc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%U.length}function cc(a,b){var c=16384===(a.mode&61440)?(c=oc(a,"x"))?c:a.O.lookup?0:2:54;if(c)throw new S(c);for(c=U[nc(a.id,b)];c;c=c.Ga){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.O.lookup(a,b)}
function ac(a,b,c,d){a=new kc(a,b,c,d);b=nc(a.parent.id,a.name);a.Ga=U[b];return U[b]=a}function pc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function oc(a,b){if(ic)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function qc(a,b){try{return cc(a,b),20}catch(c){}return oc(a,"wx")}function W(a){a=gc[a];if(!a)throw new S(8);return a}
var $b={open(a){a.V=fc[a.node.rdev].V;a.V.open?.(a)},ea(){throw new S(70);}};function Vb(a,b){fc[a]={V:b}}function rc(a,b){var c="/"===b;if(c&&ec)throw new S(10);if(!c&&b){var d=V(b,{wa:!1});b=d.path;d=d.node;if(d.la)throw new S(10);if(16384!==(d.mode&61440))throw new S(54);}b={type:a,Xa:{},za:b,Fa:[]};a=a.ba(b);a.ba=b;b.root=a;c?ec=a:d&&(d.la=b,d.ba&&d.ba.Fa.push(b))}
function sc(a,b,c){var d=V(a,{parent:!0}).node;a=Lb(a);if(!a||"."===a||".."===a)throw new S(28);var e=qc(d,a);if(e)throw new S(e);if(!d.O.ka)throw new S(63);return d.O.ka(d,a,b,c)}function X(a){return sc(a,16895,0)}function tc(a,b,c){"undefined"==typeof c&&(c=b,b=438);sc(a,b|8192,c)}function uc(a,b){if(!Ob(a))throw new S(44);var c=V(b,{parent:!0}).node;if(!c)throw new S(44);b=Lb(b);var d=qc(c,b);if(d)throw new S(d);if(!c.O.symlink)throw new S(63);c.O.symlink(c,b,a)}
function lc(a){a=V(a).node;if(!a)throw new S(44);if(!a.O.readlink)throw new S(28);return Ob(mc(a.parent),a.O.readlink(a))}
function vc(a,b){if(""===a)throw new S(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}var d=b&64?("undefined"==typeof d?438:d)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Jb(a);try{e=V(a,{va:!(b&131072)}).node}catch(f){}}c=!1;if(b&64)if(e){if(b&128)throw new S(20);}else e=sc(a,d,0),c=!0;if(!e)throw new S(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new S(54);
if(!c&&(d=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==pc(b)||b&512)?31:oc(e,pc(b)):44))throw new S(d);if(b&512&&!c){d=e;d="string"==typeof d?V(d,{va:!0}).node:d;if(!d.O.Z)throw new S(63);if(16384===(d.mode&61440))throw new S(31);if(32768!==(d.mode&61440))throw new S(28);if(c=oc(d,"w"))throw new S(c);d.O.Z(d,{size:0,timestamp:Date.now()})}b&=-131713;e={node:e,path:mc(e),flags:b,seekable:!0,position:0,V:e.V,La:[],error:!1};d=-1;e=Object.assign(new jc,e);if(-1==d)a:{for(d=0;4096>=d;d++)if(!gc[d])break a;
throw new S(33);}e.fd=d;gc[d]=e;e.V.open&&e.V.open(e);!h.logReadFiles||b&1||(wc||={},a in wc||(wc[a]=1))}function xc(a,b,c){if(null===a.fd)throw new S(8);if(!a.seekable||!a.V.ea)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.V.ea(a,b,c);a.La=[]}var yc;
function Y(a,b,c){a=Jb("/dev/"+a);var d=dc(!!b,!!c);zc||=64;var e=zc++<<8|0;Vb(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,l,m,p){for(var k=0,q=0;q<p;q++){try{var y=b()}catch(u){throw new S(29);}if(void 0===y&&0===k)throw new S(6);if(null===y||void 0===y)break;k++;l[m+q]=y}k&&(f.node.timestamp=Date.now());return k},write(f,l,m,p){for(var k=0;k<p;k++)try{c(l[m+k])}catch(q){throw new S(29);}p&&(f.node.timestamp=Date.now());return k}});tc(a,d,e)}
for(var zc,Ac={},wc,Bc=a=>0===a%4&&(0!==a%100||0===a%400),Cc=[31,29,31,30,31,30,31,31,30,31,30,31],Dc=[31,28,31,30,31,30,31,31,30,31,30,31],Ec=(a,b,c,d)=>{function e(g,r,v){for(g="number"==typeof g?g.toString():g||"";g.length<r;)g=v[0]+g;return g}function f(g,r){return e(g,r,"0")}function l(g,r){function v(A){return 0>A?-1:0<A?1:0}var w;0===(w=v(g.getFullYear()-r.getFullYear()))&&0===(w=v(g.getMonth()-r.getMonth()))&&(w=v(g.getDate()-r.getDate()));return w}function m(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-
1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function p(g){var r=g.fa;for(g=new Date((new Date(g.ga+1900,0,1)).getTime());0<r;){var v=g.getMonth(),w=(Bc(g.getFullYear())?Cc:Dc)[v];if(r>w-g.getDate())r-=w-g.getDate()+1,g.setDate(1),11>v?g.setMonth(v+1):(g.setMonth(0),g.setFullYear(g.getFullYear()+
1));else{g.setDate(g.getDate()+r);break}}v=new Date(g.getFullYear()+1,0,4);r=m(new Date(g.getFullYear(),0,4));v=m(v);return 0>=l(r,g)?0>=l(v,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var k=C[d+40>>2];d={Ja:B[d>>2],Ia:B[d+4>>2],na:B[d+8>>2],sa:B[d+12>>2],oa:B[d+16>>2],ga:B[d+20>>2],$:B[d+24>>2],fa:B[d+28>>2],Ya:B[d+32>>2],Ha:B[d+36>>2],Ka:k?k?R(x,k):"":""};c=c?R(x,c):"";k={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in k)c=c.replace(new RegExp(q,"g"),k[q]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),u="January February March April May June July August September October November December".split(" ");k={"%a":g=>y[g.$].substring(0,
3),"%A":g=>y[g.$],"%b":g=>u[g.oa].substring(0,3),"%B":g=>u[g.oa],"%C":g=>f((g.ga+1900)/100|0,2),"%d":g=>f(g.sa,2),"%e":g=>e(g.sa,2," "),"%g":g=>p(g).toString().substring(2),"%G":p,"%H":g=>f(g.na,2),"%I":g=>{g=g.na;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":g=>{for(var r=0,v=0;v<=g.oa-1;r+=(Bc(g.ga+1900)?Cc:Dc)[v++]);return f(g.sa+r,3)},"%m":g=>f(g.oa+1,2),"%M":g=>f(g.Ia,2),"%n":()=>"\n","%p":g=>0<=g.na&&12>g.na?"AM":"PM","%S":g=>f(g.Ja,2),"%t":()=>"\t","%u":g=>g.$||7,"%U":g=>f(Math.floor((g.fa+7-
g.$)/7),2),"%V":g=>{var r=Math.floor((g.fa+7-(g.$+6)%7)/7);2>=(g.$+371-g.fa-2)%7&&r++;if(r)53==r&&(v=(g.$+371-g.fa)%7,4==v||3==v&&Bc(g.ga)||(r=1));else{r=52;var v=(g.$+7-g.fa-1)%7;(4==v||5==v&&Bc(g.ga%400-1))&&r++}return f(r,2)},"%w":g=>g.$,"%W":g=>f(Math.floor((g.fa+7-(g.$+6)%7)/7),2),"%y":g=>(g.ga+1900).toString().substring(2),"%Y":g=>g.ga+1900,"%z":g=>{g=g.Ha;var r=0<=g;g=Math.abs(g)/60;return(r?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":g=>g.Ka,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");
for(q in k)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),k[q](d)));c=c.replace(/\0\0/g,"%");q=Qb(c,!1);if(q.length>b)return 0;t.set(q,a);return q.length-1},Fc=Array(256),Gc=0;256>Gc;++Gc)Fc[Gc]=String.fromCharCode(Gc);Ja=Fc;L=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Ma=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};N.push(0,1,void 0,1,null,1,!0,1,!1,1);h.count_emval_handles=()=>N.length/2-5-Qa.length;
hb=h.UnboundTypeError=((a,b)=>{var c=Va(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");[44].forEach(a=>{bc[a]=new S(a);bc[a].stack="<generic error, no stack>"});U=Array(4096);rc(T,"/");X("/tmp");X("/home");
X("/home/web_user");(function(){X("/dev");Vb(259,{read:()=>0,write:(d,e,f,l)=>l});tc("/dev/null",259);Ub(1280,Xb);Ub(1536,Yb);tc("/dev/tty",1280);tc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Nb(a).byteLength);return a[--b]};Y("random",c);Y("urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");rc({ba(){var b=ac(a,"fd",16895,73);b.O={lookup(c,d){var e=W(+d);c={parent:null,ba:{za:"fake"},O:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Ic={o:(a,b,c)=>{var d=new Ga(a);C[d.ma+16>>2]=0;C[d.ma+4>>2]=b;C[d.ma+8>>2]=c;Ha=a;Ia++;throw Ha;},B:()=>{F("")},t:()=>{},D:(a,b,c,d)=>{b=I(b);M(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(x[e])},aa:null})},C:a=>M(a,Ta),n:(a,b,c)=>{b=I(b);M(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Ua(b,c),aa:null})},f:(a,b,c,d,e,f,l)=>{var m=ab(b,c);a=
I(a);a=lb(a);e=gb(d,e);$a(a,function(){kb(`Cannot call ${a} due to unbound types`,m)},b-1);Na(m,p=>{var k=[p[0],null].concat(p.slice(1));p=a;var q=a;var y=e,u=k.length;if(2>u)throw new L("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==k[1]&&!1,r=Xa(k),v="void"!==k[0].name;y=[q,La,y,f,Wa,k[0],k[1]];for(var w=0;w<u-2;++w)y.push(k[w+2]);if(!r)for(w=g?1:2;w<k.length;++w)null!==k[w].aa&&y.push(k[w].aa);r=Xa(k);w=k.length;var A="",H="";for(u=0;u<w-2;++u)A+=
(0!==u?", ":"")+"arg"+u,H+=(0!==u?", ":"")+"arg"+u+"Wired";A=`\n        return function (${A}) {\n        if (arguments.length !== ${w-2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${w-2}');\n        }`;r&&(A+="var destructors = [];\n");var Rb=r?"destructors":"null",Pa="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");g&&(A+="var thisWired = classParam['toWireType']("+Rb+", this);\n");for(u=
0;u<w-2;++u)A+="var arg"+u+"Wired = argType"+u+"['toWireType']("+Rb+", arg"+u+");\n",Pa.push("argType"+u);g&&(H="thisWired"+(0<H.length?", ":"")+H);A+=(v||l?"var rv = ":"")+"invoker(fn"+(0<H.length?", ":"")+H+");\n";if(r)A+="runDestructors(destructors);\n";else for(u=g?1:2;u<k.length;++u)g=1===u?"thisWired":"arg"+(u-2)+"Wired",null!==k[u].aa&&(A+=`${g}_dtor(${g});\n`,Pa.push(`${g}_dtor`));v&&(A+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [Sb,Kc]=[Pa,A+"}\n"];Sb.push(Kc);k=Ya(Sb)(...y);
q=Va(q,k);k=b-1;if(!h.hasOwnProperty(p))throw new Ma("Replacing nonexistent public symbol");void 0!==h[p].Y&&void 0!==k?h[p].Y[k]=q:(h[p]=q,h[p].Ba=k);return[]})},c:(a,b,c,d,e)=>{b=I(b);-1===e&&(e=4294967295);e=m=>m;if(0===d){var f=32-8*c;e=m=>m<<f>>>f}var l=b.includes("unsigned")?function(m,p){return p>>>0}:function(m,p){return p};M(a,{name:b,fromWireType:e,toWireType:l,argPackAdvance:8,readValueFromPointer:mb(b,c,0!==d),aa:null})},a:(a,b,c)=>{function d(f){return new e(t.buffer,C[f+4>>2],C[f>>2])}
var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=I(c);M(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Da:!0})},m:(a,b)=>{b=I(b);var c="std::string"===b;M(a,{name:b,fromWireType:function(d){var e=C[d>>2],f=d+4;if(c)for(var l=f,m=0;m<=e;++m){var p=f+m;if(m==e||0==x[p]){l=l?R(x,l,p-l):"";if(void 0===k)var k=l;else k+=String.fromCharCode(0),k+=l;l=p+1}}else{k=Array(e);for(m=0;m<e;++m)k[m]=String.fromCharCode(x[f+m]);k=k.join("")}Q(d);
return k},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new L("Cannot pass non-string to std::string");var l=c&&f?ob(e):e.length;var m=Hc(4+l+1),p=m+4;C[m>>2]=l;if(c&&f)nb(e,x,p,l+1);else if(f)for(f=0;f<l;++f){var k=e.charCodeAt(f);if(255<k)throw Q(p),new L("String has UTF-16 code units that do not fit in 8 bits");x[p+f]=k}else for(f=0;f<l;++f)x[p+f]=e[f];
null!==d&&d.push(Q,m);return m},argPackAdvance:8,readValueFromPointer:Sa,aa(d){Q(d)}})},g:(a,b,c)=>{c=I(c);if(2===b){var d=rb;var e=sb;var f=tb;var l=m=>qa[m>>1]}else 4===b&&(d=ub,e=vb,f=wb,l=m=>C[m>>2]);M(a,{name:c,fromWireType:m=>{for(var p=C[m>>2],k,q=m+4,y=0;y<=p;++y){var u=m+4+y*b;if(y==p||0==l(u))q=d(q,u-q),void 0===k?k=q:(k+=String.fromCharCode(0),k+=q),q=u+b}Q(m);return k},toWireType:(m,p)=>{if("string"!=typeof p)throw new L(`Cannot pass non-string to C++ string type ${c}`);var k=f(p),q=Hc(4+
k+b);C[q>>2]=k/b;e(p,q+4,k+b);null!==m&&m.push(Q,q);return q},argPackAdvance:8,readValueFromPointer:Sa,aa(m){Q(m)}})},E:(a,b)=>{b=I(b);M(a,{Ea:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},A:(a,b,c)=>x.copyWithin(a,b,b+c),r:(a,b,c)=>{a=O(a);b=xb(b,"emval::as");return yb(b,c,a)},p:(a,b,c,d)=>{a=zb[a];b=O(b);return a(null,b,c,d)},q:(a,b,c,d,e)=>{a=zb[a];b=O(b);c=Bb(c);return a(b,b[c],d,e)},b:Ra,H:(a,b)=>{a=O(a);b=O(b);return a==b},i:a=>{if(0===a)return P(Cb());a=Bb(a);return P(Cb()[a])},
e:(a,b,c)=>{b=Eb(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,l=[];0===c&&l.push("obj");for(var m=["retType"],p=[d],k=0;k<a;++k)l.push("arg"+k),m.push("argType"+k),p.push(b[k]),e+=`  var arg${k} = argType${k}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[k].argPackAdvance;e+=`  var rv = ${1===c?"new func":"func.call"}(${l.join(", ")});\n`;d.Ea||(m.push("emval_returnValue"),p.push(yb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");
m.push(e+"};\n");a=Ya(m)(...p);c=`methodCaller<(${b.map(q=>q.name).join(", ")}) => ${d.name}>`;return Db(Va(c,a))},G:a=>{a=Bb(a);return P(h[a])},j:(a,b)=>{a=O(a);b=O(b);return P(a[b])},h:a=>{9<a&&(N[a+1]+=1)},l:a=>P(Bb(a)),d:a=>{var b=O(a);Wa(b);Ra(a)},F:(a,b)=>{a=xb(a,"_emval_take_value");a=a.readValueFromPointer(b);return P(a)},y:()=>{F("OOM")},v:(a,b)=>{var c=0;Hb().forEach((d,e)=>{var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)t[e++]=d.charCodeAt(f);t[e]=0;c+=d.length+1});return 0},w:(a,b)=>
{var c=Hb();C[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);C[b>>2]=d;return 0},z:function(a){try{var b=W(a);if(null===b.fd)throw new S(8);b.pa&&(b.pa=null);try{b.V.close&&b.V.close(b)}catch(c){throw c;}finally{gc[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof Ac||"ErrnoError"!==c.name)throw c;return c.ja}},x:function(a,b,c,d){try{a:{var e=W(a);a=b;for(var f,l=b=0;l<c;l++){var m=C[a>>2],p=C[a+4>>2];a+=8;var k=e,q=f,y=t;if(0>p||0>q)throw new S(28);if(null===k.fd)throw new S(8);
if(1===(k.flags&2097155))throw new S(8);if(16384===(k.node.mode&61440))throw new S(31);if(!k.V.read)throw new S(28);var u="undefined"!=typeof q;if(!u)q=k.position;else if(!k.seekable)throw new S(70);var g=k.V.read(k,y,m,p,q);u||(k.position+=g);var r=g;if(0>r){var v=-1;break a}b+=r;if(r<p)break;"undefined"!=typeof f&&(f+=r)}v=b}C[d>>2]=v;return 0}catch(w){if("undefined"==typeof Ac||"ErrnoError"!==w.name)throw w;return w.ja}},s:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;
try{if(isNaN(b))return 61;var f=W(a);xc(f,b,d);Ea=[f.position>>>0,(G=f.position,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];B[e>>2]=Ea[0];B[e+4>>2]=Ea[1];f.pa&&0===b&&0===d&&(f.pa=null);return 0}catch(l){if("undefined"==typeof Ac||"ErrnoError"!==l.name)throw l;return l.ja}},k:function(a,b,c,d){try{a:{var e=W(a);a=b;for(var f,l=b=0;l<c;l++){var m=C[a>>2],p=C[a+4>>2];a+=8;var k=e,q=m,y=p,u=f,g=t;if(0>y||0>u)throw new S(28);if(null===k.fd)throw new S(8);
if(0===(k.flags&2097155))throw new S(8);if(16384===(k.node.mode&61440))throw new S(31);if(!k.V.write)throw new S(28);k.seekable&&k.flags&1024&&xc(k,0,2);var r="undefined"!=typeof u;if(!r)u=k.position;else if(!k.seekable)throw new S(70);var v=k.V.write(k,g,q,y,u,void 0);r||(k.position+=v);var w=v;if(0>w){var A=-1;break a}b+=w;"undefined"!=typeof f&&(f+=w)}A=b}C[d>>2]=A;return 0}catch(H){if("undefined"==typeof Ac||"ErrnoError"!==H.name)throw H;return H.ja}},u:(a,b,c,d)=>Ec(a,b,c,d)},Z=function(){function a(c){Z=
c.exports;oa=Z.I;c=oa.buffer;h.HEAP8=t=new Int8Array(c);h.HEAP16=z=new Int16Array(c);h.HEAPU8=x=new Uint8Array(c);h.HEAPU16=qa=new Uint16Array(c);h.HEAP32=B=new Int32Array(c);h.HEAPU32=C=new Uint32Array(c);h.HEAPF32=ra=new Float32Array(c);h.HEAPF64=sa=new Float64Array(c);cb=Z.N;ua.unshift(Z.J);D--;h.monitorRunDependencies?.(D);0==D&&(null!==xa&&(clearInterval(xa),xa=null),E&&(c=E,E=null,c()));return Z}var b={a:Ic};D++;h.monitorRunDependencies?.(D);if(h.instantiateWasm)try{return h.instantiateWasm(b,
a)}catch(c){n(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}za||=h.locateFile?ya("rsiscool.wasm")?"rsiscool.wasm":h.locateFile?h.locateFile("rsiscool.wasm",fa):fa+"rsiscool.wasm":(new URL("rsiscool.wasm",import.meta.url)).href;Da(b,function(c){a(c.instance)}).catch(ba);return{}}(),ib=a=>(ib=Z.K)(a),Q=a=>(Q=Z.L)(a),Hc=a=>(Hc=Z.M)(a);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Z.P)(a,b,c,d,e);h.dynCall_viijii=(a,b,c,d,e,f,l)=>(h.dynCall_viijii=Z.Q)(a,b,c,d,e,f,l);
h.dynCall_iiiiij=(a,b,c,d,e,f,l)=>(h.dynCall_iiiiij=Z.R)(a,b,c,d,e,f,l);h.dynCall_iiiiijj=(a,b,c,d,e,f,l,m,p)=>(h.dynCall_iiiiijj=Z.S)(a,b,c,d,e,f,l,m,p);h.dynCall_iiiiiijj=(a,b,c,d,e,f,l,m,p,k)=>(h.dynCall_iiiiiijj=Z.T)(a,b,c,d,e,f,l,m,p,k);var Jc;E=function Lc(){Jc||Mc();Jc||(E=Lc)};
function Mc(){function a(){if(!Jc&&(Jc=!0,h.calledRun=!0,!pa)){h.noFSInit||yc||(yc=!0,h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Y("stdin",h.stdin):uc("/dev/tty","/dev/stdin"),h.stdout?Y("stdout",null,h.stdout):uc("/dev/tty","/dev/stdout"),h.stderr?Y("stderr",null,h.stderr):uc("/dev/tty1","/dev/stderr"),vc("/dev/stdin",0),vc("/dev/stdout",1),vc("/dev/stderr",1));ic=!1;Fa(ua);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=
[h.postRun]);h.postRun.length;){var b=h.postRun.shift();va.unshift(b)}Fa(va)}}if(!(0<D)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)wa();Fa(ta);0<D||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Mc();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default rsiscool;
